### PR TITLE
WIP Fleet with routes and real data

### PR DESCRIPTION
**Pull request by CharlyJazz**
Signed-off-by: charlyjazz <carlosjazzc1@gmail.com>

### Changes description

Implement React Router in Fleet Section

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #N/A

### CODE REVIEW

**Comment by hectorerb** [comment]
@CharlyJazz you should fix all warnings for CircleCi is successful

**Comment by hectorerb** [comment]
@CharlyJazz could you squash this commits?

captura de pantalla 2018-03-06 a la s 17 19 32

**Comment by ajsb85** [comment]
Hi, @CharlyJazz 
This commit message is invalid
image

**Comment by ajsb85** [comment]
@CharlyJazz Why you closed this PR?

**Comment by CharlyJazz** [comment]
This PR was replaced by
https://github.com/flyve-mdm/web-mdm-dashboard/pull/433

**Pull request closed without merging**
