### PR TITLE
Redesign the Project Site's Contact page

### PR DESCRIPTION
**Pull request by E1matheus**
Signed-off-by: Esteban Matheus <ematheus@teclib.com>

### Main Goal

Redesign the Project Site's "Contact" page to make it more elegant.

### Objectives

* Use the Office UI Fabric components.
* Follow the Microsoft's support page as template. 

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@E1matheus |10|
|@gianfranco97 |14|

### References

Closes #N/A
Related #1049
Depends on #N/A

### CODE REVIEW

**Comment by E1matheus** [comment]
Started re-arranging some elements to achieve a new look, I'm attaching some images showing the original design versus the new protoype's first draft. 

**ORIGINAL:**
screen2 contact - original version - desktop size

**PROTOTYPE:**
screen3 contact - prototype - desktop size

iPad size:
screen4 - ipad size

**Comment by E1matheus** [comment]
* Added the FlyVE logo to the main Banner in the "Contact" page.
* Created a CTA (call to action) button for the Chat option.
* Re-arranged some paragraphs to improve the layout.


**iPad Pro size:**

screen1 - ipad pro size

**Kindle Fire size:**

screen2 - kindle fire size

**Desktop size:**

screen3 - desktop size

**Comment by Gianfranco97** [comment]
1. I don't like how it looks at the background color at the first section, it looks like a third header, which I don't like.

2. The image is too large, besides I still don't get the location and the chosen image.

3. Do not add the cite after the last button.

4. The last section (location, phone, and email) we can separate it into cards, with a header of one color and a body of another, but always keep the same size.

**Comment by E1matheus** [comment]
Regarding the recent queries and requests:

1. I picked that background color in order to emulate the style of the microsoft contact page. I could get rid of the bottom border to make it look more subtle, or choose an even lighter grey for it.

contact-page-comparison

2. I chose to add the FlyVEmdm logo because it literally shows up in every single social media page included in our contact options list, I put it at the top left corner to grab the attention of the visitor, I think it could help reinforce our mark and our identity, and make our users feel more comfortable when visiting our external social media pages. I agree it is too big though, no problem, I´ll adjust the size.

social media pages

3. Understood, I'll re-arrange the position of the quote.
4. Sure thing, I'll work on the creation of the cards.

**Comment by E1matheus** [comment]
## Aug 23rd update:

* Made some tweeks to the Css of the info cards, created a new header for them and modified the overall size.
* Added some margin to the left of the Main logo, and created breakpoints for it to make it responsive.
* Increased the margin at the top of the info cards row to give it more breathing room against the CTA button.

**iPhone X size:**

screen1 - iphonex size

**iPad Pro size:**

screen2 - ipad pro size

**Desktop size:**

screen3 - desktop size

**Comment by Gianfranco97** [comment]
1. The header of the cards is too large, reduce the size of these considerably
2. Centers the content of the cards vertically, not only horizontally
3. The image of the logo is still too large, and I find it excessive that the column of this occupies half of the screen
4. Try to change the section on social networks. You could copy a bit of how it is done in the "news" articles, but leaving the name of the channel and the links

**Comment by E1matheus** [comment]
## Aug 28th Update:

* Decreased the size of the info cards banner (got rid of some extra padding).
* Decreased the size of the main logo (including breakpoints amendments).
* Created new icons for Ravada in svg format using Inkscape. Made some samples in png format.

**Desktop size:**
screen1 - desktop size

**Ravada icon sample 1:**
ravada icon sample 1

**Ravada icon sample 2:**
ravada icon sample 2

**Ravada icon sample 3:**
ravada icon sample 3

**Comment by E1matheus** [comment]
## Aug 29th Update:

* Alexander told me to aim for a silhouette style for the Ravada icons so it can blend easily with rest of FlyVE Products icons.
* Created a silhouette variant for the Ravada logo in both white and black colors using Inkscape (svg format).
* Created multiple background shapes for the Ravada logo icons: square with simple corners, square with round corners (adding shine and shadows), and square with round corners 
  and hard shadows, using Inkscape (svg format).
* Tried several fonts to replicate the look and feel of the FlyVE mdm logo text, in the end I concluded 
  that Trebuchet MS was the closest to what I was looking for.
* Made some samples in png format.

**Ravada logo (Silhouette - Black):**
ravada icon silhouette - black sample 1

**Ravada Icon (Square - Simple corners):**
ravada icon square - simple corners sample 1
ravada icon square - simple corners sample 2
ravada icon square - simple corners sample 3
ravada icon square - simple corners sample 4

**Ravada Icon (Square - Rounded corners - Shine and Shadows):**
ravada icon square - rounded corners sample 1
ravada icon square - rounded corners sample 2
ravada icon square - rounded corners sample 3
ravada icon square - rounded corners sample 4

**Ravada Icon (Square - Rounded corners - Hard Shadows):**
ravada icon square - rounded corners - hard shadows sample 1
ravada icon square - rounded corners - hard shadows sample 2
ravada icon square - rounded corners - hard shadows sample 3
ravada icon square - rounded corners - hard shadows sample 4

**Ravada Icon (Square - Rounded corners - Hard Shadows - With Text):**
ravada icon with title sample

**Comment by E1matheus** [comment]
## Aug 30th Update:

* Imported the share-bar assets from the "includes" directory, added the new set of icons and started making some tests.
* Changed the size and position of the icons.
* Removed the tumblr, Pinterest and Linkedin icons, and added the telegram icon instead.

**Desktop size:**
screen1 - desktop size

**iPad Pro size:**
screen2 - ipad pro size

**Comment by E1matheus** [comment]
## Sep 4th Update:

* The buttons in the Social media row were leading to blank screens.
* Decided to include a link inside the buttons to make them more search bot friendly. Performed some tests, the buttons now lead to their correspondent social media pages. 

screen1 - desktop size

screen2 - desktop size

screen3 - desktop size

screen4 - desktop size

screen5 - desktop size

**Comment by E1matheus** [comment]
## Sep 5th Update:

* Modiffied the size of the social network buttons to make them all the same, however a scroll bar appeared on the right, I'll have to remove it.
* Increased the margin of the info card banner to correct the spacing.

screen3 - ipad pro size

**Comment by E1matheus** [comment]
## Sep 6th Update:

* I'm adding some reference files for the Ravada logo in both English and French.

**English:**
ravada reference english

**French:**
ravada reference french

**Download links:**
[Ravada logo reference chart.pdf](https://github.com/TECLIB/ravada/files/2357627/Ravada.logo.reference.chart.pdf)
[Logo Ravada référence.pdf](https://github.com/TECLIB/ravada/files/2357629/Logo.Ravada.reference.pdf)

**Comment by E1matheus** [comment]
* Corrected a typo on the previous documents, they now say "Ravada VDI":

**English:**
ravada reference english

**French:**
ravada reference french

**Download Links:**
[Ravada logo reference chart.pdf](https://github.com/TECLIB/ravada/files/2357706/Ravada.logo.reference.chart.pdf)
[Logo Ravada référence.pdf](https://github.com/TECLIB/ravada/files/2357707/Logo.Ravada.reference.pdf)

**Comment by E1matheus** [comment]
## Sep 13th Update:

- Amended the Social network icon buttons, they're now the same size, and the icons and text are centered. I removed the underline effect "On Hover".
- Corrected the column size for the text in the Main Contact banner. The space between the text and the main logo is now narrower.
- Added margin to the info cards so they look like separate items instead of a single big card.

**iPad Pro size:**
screen1 - ipad pro size

**Desktop size:**
screen2 - desktop size

screen3 - desktop size

screen4 - desktop size

screen5 - desktop size

screen6 - desktop size

screen7 - desktop size

**Comment by Naylin15** [comment]
captura de pantalla 2018-09-14 a la s 12 13 20 p m
captura de pantalla 2018-09-14 a la s 12 13 31 p m

Hi,

I think we can divide the page in two sections, one with the Teclib’ information and the second with our assistance channels and social network

The sections could be differentiated by the background color

1. We could remove the Contact us line and replace it by: Get in touch with us at any time (this should be highlighted)
We can keep the following text
A Teclib’ expert will answer your request and provide you with all the information and advice you need about: our Products, Partnership Programs, Training Courses and Support solutions.
2. Remove the quote but not the information
“The connexion between open source Communities, Partners, Customers, and R&D Organizations, is made simple and streamlined with Teclib’”
3. Teclib’ Adress - Phone - Email - Customer support (We could add the customer support link)
4. Remove theses sentences and replace it by: If you need assistance, you can also find us on … (Should be hightligted)
5. Telegram - IRC - Reddit - (The rest of our social networks)

**Comment by Naylin15** [comment]
Hi @Gianfranco97 

As previous conversation I added the new paragraphs for the page

captura de pantalla 2018-09-19 a la s 11 48 37 a m

**Comment by Gianfranco97** [comment]
localhost_4000_web-mdm-dashboard_contact 6

**Pull request merged**
