### PR TITLE
Add english strings to transifex project

### LINKED ISSUE #294: Translations and support to I18N/L10N
### Observed Results:

The application does not support multiple languages
  
### Expected behavior:

The application should have the functionality to change the language in which messages and and all static texts are rendered

---------------------
It is necessary to investigate what is the best technology to implement multiple languages in the application

Options:

- [ ] Transifex CLI
- [x] WinJS (I18N/L10N)
- [x] React (I18N/L10N)

### Testing and CI:

- A series of automated tests should be created to verify if the translations behave as they should.
- The status of the application will be monitored by CircleCI and not by TravisCI

### Libraries to test feasibility

- https://github.com/JSxMachina/react-i18nify
- https://github.com/NunoPinheiro/react-i18n-helper

### react-i18n-helper: 

[Example](https://react-theme-1.herokuapp.com/)

This is a simple way to implement i18n in a React application using Redux and a High Order Component to wrap the entire application

The necessary libraries are:
- node-polyglot (Translation tools)
- redux (state manager)

**Important**: 

- The library https://github.com/JSxMachina/react-i18nify is not used directly, since the code is flawed and depends of libraries that are not necessary for our projects, such as `promise-polyfill`. Instead it was refactored and i created the HOC.

- The strings of each translation are not added to the bundle file of the application which prevents it from increasing its size:

image

### react-i18nify:
[In this example the library is used to enable i18n](https://streamable.com/knbsc)

**Important**:  Is more complicated to use, and if it is used in the way you show in your documentation, all the strings of each language will be added in the bundle file of the application and will be heavie:

image

### PR DESCRIPTION
**Pull request by CharlyJazz**
### Changes description

I am adding the strings in English to the Transifex project of the Dashboard

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #294

### CODE REVIEW

**Comment by CharlyJazz** [comment]
@ajsb85 Ready for review, I already finished the About section

**Comment by hectorerb** [comment]
@CharlyJazz it commit  message https://github.com/flyve-mdm/web-mdm-dashboard/commit/9145b5bab5813eb3516353cdbee5e1c62ca28bbd  you could do a rebase and not generate it

**Comment by hectorerb** [comment]
@CharlyJazz from your branch charlyjazz-transifez

git fetch origin develop
git rebase origin/develop

In this way you don't generate unnecessary commits

**Comment by Gianfranco97** [comment]
```
$ 
git fetch origin develop 
$ git rebase origin develop
```

**Comment by CharlyJazz** [comment]
@hectorerb Thank for the tip, from now on i going to using it

**Pull request merged**
