### PR TITLE
Create account form

### PR DESCRIPTION
**Pull request by Gianfranco97**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue #91
Close: #150 

## What is the new behavior?

  localhost_3000_signin_imageprofile photo537050373369735084 jpg login realname firstname title option 1 location option 1 defaultprofile option 1 password passwordconfirmation 0 phone mobilephone phone2 administrativenumber cat 1

  localhost_3000_signin_imageprofile photo537050373369735084 jpg login realname firstname title option 1 location option 1 defaultprofile option 1 password passwordconfirmation 0 phone mobilephone phone2 administrativenumber cat 2

  localhost_3000_signin_imageprofile photo537050373369735084 jpg login realname firstname title option 1 location option 1 defaultprofile option 1 password passwordconfirmation 0 phone mobilephone phone2 administrativenumber cat 3

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajsb85** [comment]
This form is to add a new registered user from a registered user logged?

**Comment by Gianfranco97** [comment]
The conflicts were resolved

**Comment by Gianfranco97** [comment]
@ajsb85 It is a form for registering new users

**Comment by Gianfranco97** [comment]
I'm going to simplify the registration form

**Comment by hectorerb** [comment]
Hi @Gianfranco97, could you create a simpler form? Only login, email and password

**Comment by Gianfranco97** [comment]
I'm going to simplify the registration form

**Comment by Gianfranco97** [comment]
Done 
  
  localhost_3000_signin

**Pull request merged**
