### PR TITLE
Screenshots for all pages

### PR DESCRIPTION
**Pull request by Gianfranco97**
### Changes description

In this PR, take screenshots automatically to:
- Invitations
- Users
- Logout

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Close: #878

### CODE REVIEW

**Comment by Gianfranco97** [comment]
I have had many problems to be able to run the server's response to the captcha image using cypress. I have tried in many different ways but they all have  resulted in the same result or even a worse error.

captura de pantalla 2018-06-18 a la s 5 03 53 p m


These are some of the reference links with which I have been working:

- https://docs.cypress.io/api/utilities/blob.html
- https://docs.cypress.io/api/commands/route.html
- https://docs.cypress.io/guides/guides/network-requests.html
- https://docs.cypress.io/api/commands/server.html
- https://github.com/cypress-io/cypress/issues/170

**Comment by Gianfranco97** [comment]
Some non-functional examples:
``` js
        cy.fixture('images/captcha.jpeg').then((captcha) => {
            cy.route({
                method: 'GET',
                url: `${glpiApiLink}/PluginFlyvemdmdemoCaptcha/603?alt=media&`,
                response: captcha
            })
        })
```
---
``` js
        cy.fixture('images/captcha.jpeg').then(dataURI => {
            Cypress.Blob.base64StringToBlob(dataURI, "image/jpeg").then((blob) => {
                cy.route({
                    method: 'GET',
                    url: `${glpiApiLink}/PluginFlyvemdmdemoCaptcha/603?alt=media&`,
                    response: {img: blob},
                    headers: {
                        'Content-Type': 'image/jpeg'
                    },
                })
            })
        })
```
---
``` js
        cy.route({
            method: 'GET',
            url: `${glpiApiLink}/PluginFlyvemdmdemoCaptcha/603?alt=media&`,
            response: cy.fixture("images/captcha.jpg")
        })
```
---
``` js
        cy.route('GET', `${glpiApiLink}/PluginFlyvemdmdemoCaptcha/603?alt=media&`, 'fixture:images/captcha.jpg')

```
---
``` js
        cy.fixture('images/captcha.jpeg').as('captcha')
        cy.route({
            method: 'GET',
            url: `${glpiApiLink}/PluginFlyvemdmdemoCaptcha/603?alt=media&`,
            response: '@captcha',
            headers: {
                'Content-Type': 'image/jpeg'
            },
        })
```

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 
We deprecated the registration page. 
The demo plugin is archived, waiting the new demo platform with OpenShift and Docker.
/cc @btry

**Comment by Gianfranco97** [comment]
So I leave the registration screen like this or do I completely eliminate that test?

**Comment by ajsb85** [comment]
@Gianfranco97 Remove the tests, but keep the screen until we launch the new demo site.

**Comment by Gianfranco97** [comment]
Fine 👍

**Pull request merged**
