### PR TITLE
Migrate to Webpack 4

### PR DESCRIPTION
**Pull request by hectorerb**
Signed-off-by: Hector Rondon <hrondon@teclib.com>

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #N/A

### CODE REVIEW

**Comment by CharlyJazz** [comment]
I believe that create-react-app uses the UglifyJsPlugin plugin. And that plugin was removed from webpack.

**Comment by CharlyJazz** [comment]
https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by hectorerb** [comment]
@CharlyJazz I'm working on migration to webpack 4, webpack 4 include several changes

**Comment by CharlyJazz** [comment]
Are you sure you can migrate to webpack without problems? Do not you prefer to wait for the create-react-app to launch the new version with webpack4?

**Comment by CharlyJazz** [comment]
https://github.com/facebook/create-react-app/issues/3878

**Comment by CharlyJazz** [comment]
The next version of create-react-app will support Sass and use webpack4

**Comment by ajsb85** [comment]
This PR depends of: https://github.com/facebook/create-react-app/pull/4077

**Pull request closed without merging**
