### PR TITLE
Get real profile data

### PR DESCRIPTION
**Pull request by Gianfranco97**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Close: #274 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Gianfranco97** [comment]
I have had several difficulties to be able to obtain the images of the user profiles, since I can not obtain it through Download a document file https://dev.flyve.org/glpi/apirest.php#special-cases

since there is no way to get the id of the image in the database. The only way I have found to be able to get these images is to create a special route aimed at the frontend of glpi, an example of these routes: https://dev.flyve.org/glpi/front/document.send.php?file= _pictures / f0 / 37_5a6b3a7ae51f0_min.jpg

But this brings another problem and that i,  in order for the server to respond satisfactorily this request is necessary to pass a specific cookie, this one should be delivered by the apirest at the time of initiating section but nevertheless at the time of making the request with the Fetch Javascrip API https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
I do not receive any. in the documentation of this API they speak of sending a parameter called 'credentials' in the options of the request, but for some reason this causes my requests to fail completely.

I am still looking for the way to be able to pass the required cookie to the server.

**Comment by Gianfranco97** [comment]
@btry Could not there be a way through the apirest to get the id of the image or download an archive with a route?

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

[users.json.zip](https://github.com/flyve-mdm/web-admin-dashboard/files/1464820/users.json.zip)

`"User.picture": "24/221_5a084effc6624.jpg"`

For the avatar in the list use this format:
https://dev.flyve.org/glpi/front/document.send.php?file=_pictures/24/221_5a084effc6624_min.jpg

For the avatar in the user page us this format:
https://dev.flyve.org/glpi/front/document.send.php?file=_pictures/24/221_5a084effc6624.jpg

**Comment by Gianfranco97** [comment]
I believe these routes without problems, my problem is the cookie.

the result:

captura de pantalla 2018-01-26 a la s 6 49 10 p m

**Comment by Gianfranco97** [comment]
the DatePicker component of react-winjs does not allow having the possibility of having empty dates. Therefore we have opted to create our own custom DatePicker component to be able to supply this need.

##### Current behavior:
captura de pantalla 2018-01-31 a la s 8 43 43 a m


captura de pantalla 2018-01-31 a la s 8 44 20 a m

##### Expected behavior:
captura de pantalla 2018-01-31 a la s 8 43 43 a m


captura de pantalla 2018-01-31 a la s 8 51 42 a m

**Pull request merged**
