### PR TITLE
Validate account

### PR DESCRIPTION
**Pull request by hectorerb**
Signed-off-by: Hector Rondon <hrondon@teclib.com>

### Changes description

- Activate account

captura de pantalla 2018-04-10 a la s 16 18 38

captura de pantalla 2018-04-10 a la s 16 19 18

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes https://github.com/flyve-mdm/web-mdm-dashboard/issues/653

### CODE REVIEW

**Comment by hectorerb** [comment]
Hi @btry 

What should be a response to a successful activation?

**Comment by ajsb85** [comment]
@hectorerb 
Use Postman and test the endpoints for the validation in the demo plugin.

**Comment by hectorerb** [comment]
@ajsb85 I'm receiving an array that contains an empty array

**Comment by ajsb85** [comment]
Debug the demo site to take a look in details about the request.
https://demo.flyve.org/
But we have the documentation in a collection of the Postman.

**Comment by btry** [comment]
Hi

> What should be a response to a successful activation

The response is normalized by GLPI. Updating an item requires HTTP POST,  then just read the spec of the API of GLPI.

I quote the documentation:

## Update item(s)

* **URL**: apirest.php/:itemtype/:id
* **Description**: Update an object (or multiple objects) existing in GLPI.
* **Method**: PUT
* **Parameters**: (Headers)
  * *Session-Token*: session var provided by [initSession](#init-session) endpoint. Mandatory.
  * *App-Token*: authorization string provided by the GLPI api configuration. Optional.
* **Parameters**: (JSON Payload)
  * *id*: the unique identifier of the itemtype passed in URL. You **could skip** this parameter by passing it in the input payload.
  * *input*: Array of objects with fields of itemtype to be updated.
               Mandatory.
               You **could provide** in each object a key named 'id' to identify the item(s) to update.
* **Returns**:
  * 200 (OK) with update status for each item.
  * 207 (Multi-Status) with id of added items and errors.
  * 400 (Bad Request) with a message indicating an error in input parameter.
  * 401 (UNAUTHORIZED).

Example usage (CURL):

```bash
$ curl -X PUT \
-H 'Content-Type: application/json' \
-H "Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62" \
-H "App-Token: f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7" \
-d '{"input": {"otherserial": "xcvbn"}}' \
'http://path/to/glpi/apirest.php/Computer/10'

< 200 OK
[{"10":true, "message": ""}]


$ curl -X PUT \
-H 'Content-Type: application/json' \
-H "Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62" \
-H "App-Token: f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7" \
-d '{"input": {"id": 11,  "otherserial": "abcde"}}' \
'http://path/to/glpi/apirest.php/Computer/'

< 200 OK
[{"11":true, "message": ""}]


$ curl -X PUT \
-H 'Content-Type: application/json' \
-H "Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62" \
-H "App-Token: f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7" \
-d '{"input": [{"id": 16,  "otherserial": "abcde"}, {"id": 17,  "otherserial": "fghij"}]}' \
'http://path/to/glpi/apirest.php/Computer/'

< 207 OK
[{"8":true, "message": ""},{"2":false, "message": "Item not found"}]
```

Then the answer is

HTTP 200 OK
[{"10":true, "message": ""}]

If you receive an empty array, I'm suspecting the request is somewhat malformed and the backend doesn't know which item to update. I'll check this

**Comment by btry** [comment]
I reproduced your issue @hectorerb 

You very likely forgot to provide the ID if the account validation item to validate.

Look the query URL requested in this picture

image

and the response
image

**Comment by hectorerb** [comment]
done, you're right! I forgot to provide the ID of the account

**Pull request merged**
