### PR TITLE
Request an inventory

### PR DESCRIPTION
**Pull request by Gianfranco97**
### Changes description

In this PR:
- Create button to request inventory 

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Close: #746

### CODE REVIEW

**Comment by Gianfranco97** [comment]
@btry  @DIOHz0r The backend always returns me a timeout (although the request is being made in the agent)

fdbw0-xvfoo

**Comment by btry** [comment]
Assuming the agent actually sends the inventory via MQTT, then the timeout may occur because the message is not received in the expected topic. This is not necessarily the fault of  the agent. 

Use a mqtt client to see on which topic the inventory is sent. In the mean  time, let's check the mqtthandler class

**Comment by rafaelje** [comment]
The agent is sending the inventory to this topic "2/agent/1162186473/Status/Inventory"

**Comment by Gianfranco97** [comment]
Done 


iumws-7kvhv

**Comment by btry** [comment]
@Gianfranco97 Maybe it would be better to put the success notification in the plugin. This way, you will receive it too, and you won't need to implement yourself.

**Comment by Gianfranco97** [comment]
Sure, no problem. If we implement it, I can easily change it

**Pull request merged**
