### PR TITLE
Breadcrumbs

### PR DESCRIPTION
**Pull request by Gianfranco97**
Signed-off-by: Gianfranco Manganiello <gmanganiello@teclib.com>

### Changes description

In this PR:
- Show the full path in the breadcrumbs and make redirects from there

captura de pantalla 2018-03-08 a la s 1 27 35 p m

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Close: #441

### CODE REVIEW

**Comment by CharlyJazz** [comment]
You could capitalize the Name of the section? Invitations instead invitation

**Comment by Gianfranco97** [comment]
@CharlyJazz Sure

**Comment by Gianfranco97** [comment]
@CharlyJazz  Done 

captura de pantalla 2018-03-08 a la s 2 23 53 p m

**Comment by CharlyJazz** [comment]
Yei

2018-03-08 14:26 GMT-04:00 Gianfranco Gesu Manganiello Tiso <
notifications@github.com>:

**Pull request merged**
