### PR TITLE
Migrate gh-pages to circle & Documentation

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Migrate gh-pages to circle
Add docker documentation

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |11|
|@rafaelje|3|
|@DIOHz0r|2|
|@hectorerb|2|

### References

Closes #N/A
Related #N/A
Depends on #N/A

### CODE REVIEW

**Comment by Naylin15** [comment]
The tests are failing because html proofer is running and taking too long with no output

Build [5442](https://circleci.com/gh/flyve-mdm/web-mdm-dashboard/5442)

**Comment by Naylin15** [comment]
I think the issue with html proofer is since the documentation folders have a lot of files, it takes more time than usually to check them and runs without output, overpassing the CI limit time of 10 min

**Comment by Naylin15** [comment]
I have been making tests trying to use circleci with the go linter, checking the docker images with go ruby and npm on my fork, I have been having issues with the ruby installation

[Circle CI Feature/migrate-ci tests](https://circleci.com/gh/Naylin15/web-mdm-dashboard-fork/tree/feature%2Fmigrate-ci)

**Comment by ajsb85** [comment]
Hi, @Naylin15 
You waste too much time with these test.
Could you use the same docker image locally and going more faster testing using SSH.
Thanks

**Comment by Naylin15** [comment]
Sure, I'll hurry to finish this PR as soon as possible 👍

**Comment by Naylin15** [comment]
I Configured the Circle Ci, installed everything it requires to run the tests, also run in background the server to make the tests locally (Rel. [#179](https://git.io/fNatU))

After some trouble shooting with the localhost link it runs on every directory

But now it gives several timeout errors and connectivity [#42](https://circleci.com/gh/Naylin15/web-mdm-dashboard-fork/42#usage-queue/containers/0)

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Server address: http://127.0.0.1:4000/web-mdm-dashboard/
Tests running: http://localhost:4000/web-mdm-dashboard/
And the jekyll config point to http://127.0.0.1:4000/web-mdm-dashboard/?

**Comment by Naylin15** [comment]
Yes, the problem is that when using the server address: http://127.0.0.1:4000/web-mdm-dashboard/ it only checks the first page it does not check all the html files in the address, for that it must run the tests on the  http://localhost:4000/web-mdm-dashboard/

From SSH
captura de pantalla 2018-08-01 a la s 12 51 30 p m

**Comment by Naylin15** [comment]
The linter is working however for how it was written, it will always return an exit code 1

Meaning failure for the CI wether it's success, example [#54](https://circleci.com/gh/Naylin15/web-mdm-dashboard-fork/54) or failure [#52](https://circleci.com/gh/Naylin15/web-mdm-dashboard-fork/52)

**Comment by Naylin15** [comment]
The process is being killed because it takes too much memory

captura de pantalla 2018-08-02 a la s 10 15 31 a m

**Comment by Naylin15** [comment]
We tried with liche at first it seemed success [#5532](https://circleci.com/gh/flyve-mdm/web-mdm-dashboard/5532)l but when checking with muffet the links it shows that liche is not making a correct validation

captura de pantalla 2018-08-02 a la s 6 28 59 p m

**Comment by Naylin15** [comment]
Success [5550](https://circleci.com/gh/flyve-mdm/web-mdm-dashboard/5555) ! 🎊

Thanks to @DIOHz0r help with the excluding pattern

Now Muffet runs only in the web-mdm-dashboard links

**Pull request merged**
