### PR TITLE
Circle CI & Transifex Integration

### PR DESCRIPTION
**Pull request by CharlyJazz**
### Integration of Transifex with Circle CI:
A unit test was created to verify if translations are available for the Dashboard Login section.

image

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

#294 

Closes #N/A

### CODE REVIEW

**Comment by CharlyJazz** [comment]
Ready for review @Gianfranco97  @hectorerb 

I'll make another PR soon with new implementations

It would be good if the following PRs were also closed #299  #296

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 and @hectorerb 

Any feedback about this PR?

Thanks

**Comment by ajsb85** [comment]
Circle CI is already activated.

**Comment by ajsb85** [comment]
Hi, @CharlyJazz 
Could you edit this commit message?
`Merge branch 'develop' of github.com:flyve-mdm/web-mdm-dashboard into…`

**Comment by ajsb85** [comment]
Hi, @CharlyJazz 
This commit message is too long: fix(circle-ci): Merge branch 'develop' of github.com:flyve-mdm/web-md…  …

Any line of the commit message cannot be longer 100 characters! This allows the message to be easier to read on GitHub as well as in various git tools.

**Comment by ajsb85** [comment]
Hi, @btry 
Could you provide information To Carlos how to edit oldest commits here?
Thank you.

**Comment by btry** [comment]
@CharlyJazz 

Assuming you want to rewrite the message of the 3 last commits

* use ```git log``` or any other mean to find the commit hash of the previous commit of the 3 last ones. Copy it in your clipboard.
* ```git rebase -i <the commit hash>```

You will get an editor with a predefined content, one line per commit to rebase (or edit in your case). 
You may want to cancel your action here. To do this, remove all lines. An empty file means "do nothing".

If you want to continue, check you got 3 commits. Replace the work **pick** by the letter **r** only for  the commits you want to edit (it means **R**eword).

Save the file. An editor will open again for the oldest commit to reword. Edit the message, and save. An other editor will open again for  each other commit. Edit the message until you finished.

**Comment by hectorerb** [comment]
Hi @CharlyJazz 

for this project we should user Circle 2.0

**Comment by CharlyJazz** [comment]
I'll work on that as soon as posible.

**Pull request merged**
