### PR TITLE
WIP Create React & CSS Architectures and new file structures

### PR DESCRIPTION
**Pull request by CharlyJazz**
Signed-off-by: charlyjazz <carlosjazzc1@gmail.com>

# Diagram of Architecture:

architecture_react

# ApplicationWebDashboard Code Prototype
seleccion_107

# CSS:

- [x] Create new file structure to management css styles with a adaptation of Inverted Triangle CSS
- [ ] separate elements of each UI component into different files with the same component name
- [ ] Use [BEM](http://getbem.com/naming/) to name classes
- [ ] Delete useles CSS files

# React

### Task: Create asynchronus components:

> The asynchronous components help to minimize the size of the main package of the application and are imported dynamically when necessary.

- [x] Create Async Containers:
    - [x] Admin Dashboard
    - [x] SignUp
    - [x] ForgotPassword
    - [x] ValidateAccount (Non-Reusable Component)
    - [x] Logout (Non-Reusable Component)

- [x] Separate reducers in different folders that contain:
    - actions creators
    - initial state
    - action types 
    - reducer
- [x] Implement Redux to management the global state of 
    - [x] I18N
    - [x] SignIn
    - [ ] SignUp
    - [ ] UI (Loading Spinners, Notifications)

### Task Change File Structure:
- [x] Remane `Utils/` folder to `shared/` 
- [x] Create `applications/` folder (Why?: Look the Diagram)
- [ ] Create and Implement `HOC` Layout for AdminDashboard Container (Navbar & Right Menu)
- [x] Implement `HOC` I18N
- [ ] Implement routers to Device, Fleets, etc
- [x] Rename folder with conventionals name (`assets/`, `containers/`, `components/`,` hoc/`)
- [ ] Change class components without state to stateless function 
- [x] Create `Logout`  Non-reusable component

### Task Optimize Rendering and Bundle

- [ ]  Implement `PureComponent`
- [ ] Improve the  React Component Lifecycle
- [ ] Remove useless npm dependencies

#### References

#367 
#369 

Closes #129

### CODE REVIEW

**Comment by Gianfranco97** [comment]
@CharlyJazz change the type of commits to 'refactor'

**Comment by CharlyJazz** [comment]
Currently Redux state management:

image

**Comment by Gianfranco97** [comment]
some problems in the styles

captura de pantalla 2018-02-26 a la s 2 15 38 p m

**Comment by CharlyJazz** [comment]
@hectorerb  @Gianfranco97  

[SignIn](https://streamable.com/xn55u)

**Comment by CharlyJazz** [comment]
@Gianfranco97  @hectorerb  @ajsb85 

[Screencast of the new SplitView (Vertical Left Menu)](https://streamable.com/v7bqm)

**Pull request closed without merging**
